### GET do mockDb trazendo os users
GET http://localhost:3001/users?page=1&perPage=15

### GET do mockDb trazendo os posts
GET http://localhost:3001/posts?page=1&perPage=15

### POST que validará o username/password na dashboard
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "username": "Bret",
    "password": "123"
}